### ISSUE TITLE
Panic when sending *mt.ToCltMinimapModes

### ISSUE THREAD

**Issue by HimbeerserverDE** [anon55555/mt#3]
### Reproducing the issue
Send *mt.ToCltMinimapModes to a Peer like this: `Peer.Send(&mt.ToCltMinimapModes{})`.
### Debug output
```
panic: interface conversion: *mt.ToCltMinimapModes is not mt.serializer: missing method serialize [recovered]
        panic: interface conversion: *mt.ToCltMinimapModes is not mt.serializer: missing method serialize

goroutine 1536 [running]:
github.com/anon55555/mt.pcall.func1()
        /home/himbeerserverde/go/pkg/mod/github.com/anon55555/mt@v0.0.0-20210623155243-152b6697e62c/zerialize.go:45 +0xea
panic({0x854020, 0xc001bd4870})
        /usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/anon55555/mt.serialize.func1()
        /home/himbeerserverde/go/pkg/mod/github.com/anon55555/mt@v0.0.0-20210623155243-152b6697e62c/zerialize.go:23 +0x56
github.com/anon55555/mt.pcall(0xc0005c6ea8)
        /home/himbeerserverde/go/pkg/mod/github.com/anon55555/mt@v0.0.0-20210623155243-152b6697e62c/zerialize.go:48 +0x7c
github.com/anon55555/mt.serialize({0x8fbba0, 0xc0000bc268}, {0x8690e0, 0xc000170140})
        /home/himbeerserverde/go/pkg/mod/github.com/anon55555/mt@v0.0.0-20210623155243-152b6697e62c/zerialize.go:23 +0x8f
github.com/anon55555/mt.Peer.Send.func1()
        /home/himbeerserverde/go/pkg/mod/github.com/anon55555/mt@v0.0.0-20210623155243-152b6697e62c/proto.go:41 +0x1b9
created by github.com/anon55555/mt.Peer.Send
        /home/himbeerserverde/go/pkg/mod/github.com/anon55555/mt@v0.0.0-20210623155243-152b6697e62c/proto.go:33 +0x3f9
```

I can't find the serialize and deserialize methods in serialize.go. It seems like they weren't generated by mkserialize.sh.

**Comment by anon55555** [comment]
> I can't find the serialize and deserialize methods in serialize.go. It seems like they weren't generated by mkserialize.sh.

ToCltMinimapModes uses manually written serialization and deserialization functions in tocltcmds.go. The real problem is that I got the method signatures wrong.
